#!/bin/sh
#
# Copyright (c) 2010-2012 Nest Labs, Inc.
# All rights reserved.
#
# Description:
# This file implements the list of services to start on system
# start-up.
#
# Source common library
. /etc/init.d/functions
# Start system services
${INITDIR}/announce start
${INITDIR}/start
${INITDIR}/watchdog start
${INITDIR}/hwclock restore
${INITDIR}/timezone check
${INITDIR}/sysctl start
/bin/dropbearkey -t dss -f /etc/dropbear/dropbear_dss_host_key
/bin/dropbearkey -t rsa -s 2048 -f /etc/dropbear/dropbear_rsa_host_key
/bin/dropbearkey -t ecdsa -s 521 -f /etc/dropbear/dropbear_ecdsa_host_key
/bin/dropbear