name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.build-matrix.outputs.matrix }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build matrix JSON from *.env files
        id: build-matrix
        run: |
          # Find all .env files in the repo, build JSON array [{ "config": "file.env" }, ...]
          MATRIX_JSON=$(ls -1 *.env | jq -Rsc 'split("\n") | map(select(length>0) | {config:.})')
          echo "matrix=$MATRIX_JSON" >> "$GITHUB_OUTPUT"

  build:
    needs: generate-matrix
    runs-on: ubuntu-latest
    continue-on-error: true

    strategy:
      matrix:
        include: ${{ fromJson(needs.generate-matrix.outputs.matrix) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true
        
      - name: Install dependencies
        run: |
          echo "set man-db/auto-update false" | sudo debconf-communicate
          sudo dpkg-reconfigure man-db
          
          sudo apt update
          sudo apt install -y \
            kmod \
            fakeroot \
            cpio \
            u-boot-tools \
            netpbm
        
      - name: Setup toolchain
        uses: cuckoo-nest/toolchain@main

      - name: Run build script
        run: ./build.sh "${{ matrix.config }}"

      - name: List cpio contents
        run: |
          cpio -ivt < ./initramfs_data.cpio

      - name: Get artifact name
        id: artifact_name
        run: |
          if [[ "${{ matrix.config }}" == *".env" ]]; then
            NAME="$(basename "${{ matrix.config }}" .env)"
            echo "name=$NAME" >> $GITHUB_OUTPUT
            exit 0
          fi
          
          NAME="$(echo -n "${{ matrix.config }}" | sed 's/^.\/configs\///' | sed -e 's/\//_/g' | sed -e 's/_defconfig$//')"
          echo "name=$NAME" >> $GITHUB_OUTPUT

      - name: Upload artifact
        uses: actions/upload-artifact@v5
        with:
          name: ${{ matrix.name || steps.artifact_name.outputs.name }}
          path: |
            ./linux/arch/arm/boot/Image
            ./linux/arch/arm/boot/uImage
            ./linux/arch/arm/boot/zImage
            ./initramfs_data.cpio
